### ISSUE TITLE
Unmet peer dependency?

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-sdk#286]
Looks like npm dedupe plays against us.

If I go to the SDK repo and run `npm install` all goes fine.
If I install `resin-sdk-preconfigured` as a dependency to some other project it works fine, too.

But when clone the resin-cli and did npm install there I've seen:
```
npm ERR! peer dep missing: resin-token@^3.0.0, required by resin-pine@5.0.1
npm ERR! peer dep missing: resin-token@^3.0.0, required by resin-request@8.3.0
```

And:
```
✔ npm ls resin-request
resin-cli@5.5.0 /Users/eugene/Work/resin-cli
├─┬ resin-sdk-preconfigured@0.1.0
│ └─┬ resin-sdk@6.0.0-beta5
│   ├── resin-request@8.3.0
│   └── UNMET PEER DEPENDENCY resin-token@3.0.0
└─┬ resin-sync@7.0.2
  └─┬ resin-sdk@5.4.0
    └── resin-request@4.1.2
```

I think here's the issue:
```
✔ ls node_modules | grep resin
resin-cli-auth
resin-cli-errors
resin-cli-form
resin-cli-visuals
resin-config-json
resin-device-config
resin-device-init
resin-device-logs
resin-device-operations
resin-device-status
resin-discoverable-services
resin-errors
resin-image-fs
resin-image-manager
resin-image-write
resin-pine
resin-register-device
resin-request
resin-sdk
resin-sdk-preconfigured
resin-settings-client
resin-settings-storage
resin-sync
resin-token

✔ npm ls resin-token
resin-cli@5.5.0 /Users/eugene/Work/resin-cli
└─┬ resin-cli-auth@1.1.2
  └── resin-token@2.4.3
```

So resin-cli-auth depends on the older version fo token which is lifted to the top-level.
At the same time `resin-request` was deduped and lifted to the top level where it now has the peer dependency... of the wrong version.

Should we remove the peer deps declarations in spite of this?
The docs (of the resin-request and resin-pine) already say the token should be injected.
---

Also `pinejs-client` is no longer a direct dependency and can be removed.

**Comment by pimterry** [comment]
Looks like this is just a problem with how npm displays this, not with the packages that get installed or where they're put. On a clean install, I end up with a node_modules folder structure including:

```
- resin-sdk @ 6.0.0-beta5
  - node_modules
     - resin-token @ 3.0.0

- resin-sdk-preconfigured @ 0.1.0
  - [no node_modules, using the top-level resin-sdk installation]
- resin-token @ 2.4.3 [from resin-sync]
- resin-request @ 8.3.0
- resin-pine @ 5.0.1
```

This means that everything is working fine (resin-sdk will find the correct version of resin-token, in its own node_modules, and use that correctly), but also that the request and pine packages genuinely aren't peer dependencies of the resin-token version they're asking for. Arguably that means that although this is working correctly, the error is correct too: they're genuinely not peers of the deps they asked for.

I'm not totally clear whether this is the correct npm behaviour, but it's certainly the _current_ npm behaviour. There's a few options I can think of to solve this:

1. Upgrade resin-sync to use the new version of resin-token. If we don't have a conflict, we'll end up with the right version of resin-token at the top level, and everybody will be happy.
2. Remove the peer deps. Arguably we don't really want a peer dependency: we want to assert that whoever's using this module is passing in a token of the right type, but npm doesn't have a mechanism for us to say that.
3. Both of the above.

I'd rather do 1. if we can, simply because this often is a useful warning, even if it's not quite as reliable or accurate as we'd like. If we do accidentally use these modules with the wrong version of resin-token, they'll potentially break, and this ensures we'll always get a warning if that happens.

I've just done a test, and it's worth also noting that this happens too for end users (i.e. if you `npm install g resin-cli` and look closely you'll get a warning about a missing peer dep for resin-token) so it really would be nice to tidy this up one way or the other fairly quickly.

**Comment by pimterry** [comment]
Github autoclose - that PR didn't actually completely fix this. PR coming to the CLI imminently which will though (by stopping it happening - for now I think having peer dep warnings come up when we have dep conflicts is moderately sensible behaviour here, just about)
