### ISSUE TITLE
Auto-publish doesn't seem to work

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-sdk#309]
v6.1.0 wasn't published to npm

**Comment by pimterry** [comment]
Ah, damn. I _think_ this happened because we have 'Build branch updates' turned off in travis, so it's not looking at master - it only monitors changes on PRs. It's tricky though, because if we turned that off in #241 to avoid duplicating build jobs and hammering the API unnecessarily.

According to https://github.com/travis-ci/travis-ci/issues/1147 I think we can fix this by re-enabling branch updates, but limiting them to only commits on master. I'm going to add that now.

**Comment by pimterry** [comment]
Now all fixed, versionbot added, definitely seems to be working. Closing!
