### ISSUE TITLE
Cannot login with token

### ISSUE THREAD

**Issue by Arwid** [resin-io/resin-sdk#377]
Resin-sdk: 6.9.0

`resin.auth.loginWithToken` doesn't log me in. I've tried valid tokens from multiple accounts.

```coffeescript
resin = require('resin-sdk')()
resin.auth.loginWithToken "A VALID TOKEN"
	.then resin.auth.isLoggedIn
	.then (isLoggedIn) ->
		console.log isLoggedIn is false
```

**Comment by pimterry** [comment]
Hi @Arwid, I've just tested this, and it's definitely working for me (using v6.12.1), and we do have automated tests that use this successfully too: https://github.com/resin-io/resin-sdk/blob/master/tests/integration/auth.spec.coffee#L81-L82.

I'd like a little more information to debug this further:

* I'm assuming you're running this in Node - is that correct? Which version?
* After you run this, is the correct token stored in `~/.resin/token`?
* What happens if you set `$JWT_TOKEN`, and run `curl --request GET --url https://api.resin.io/whoami --header 'authorization: Bearer $JWT_TOKEN'` by hand? (This is what `isLoggedIn` does under the hood).
* If you're familiar with a HTTP proxying tool (don't worry about it otherwise), like [Fiddler](http://www.telerik.com/fiddler), can you set one up in your process (e.g. using [global-tunnel](https://github.com/salesforce/global-tunnel)), and take a look at the `api.resin.io/whoami` request that the SDK is making? It should include an `authorization` header, like the curl one above, and get a 200 back if all's well, or a 401 otherwise.

**Comment by Arwid** [comment]
Hi @pimterry, thanks for the help. 

I've tried again and the same code works now (both with v6.9.0 and the latest v6.14.0) using current tokens from the dashboard (looks like they're refreshed on every login).

Closing issue. If it ever occurs again, I'll reopen with that debug information.

**Comment by pimterry** [comment]
Glad to hear it's sorted. Thanks for the report @Arwid!
