### ISSUE TITLE
ResinSupervisorLockedError is not available under errors

### ISSUE THREAD

**Issue by thgreasi** [resin-io/resin-sdk#385]

**Comment by pimterry** [comment]
@thgreasi this can now be closed, right?

**Comment by thgreasi** [comment]
@pimterry yes, thanks for the heads-up, I always forget we need `Resolves/...` for this repo to auto-close issues from PRs. But do you have any idea why 6.12.1 didn't reach npm ? All builds seem to be [done](https://travis-ci.org/resin-io/resin-sdk/jobs/274145243)!?

**Comment by pimterry** [comment]
Good spot! That's because [this job](https://travis-ci.org/resin-io/resin-sdk/jobs/274145243) quietly failed the tests on deploy (because of a spurious failure). I've now restarted it.

Generally, if you want to check the deploy, you need to look for the build with the version tag (e.g. `v6.12.1` on https://travis-ci.org/resin-io/resin-sdk/builds), and then expand the 'Deploying application' section at the bottom. Annoyingly, Travis still marks builds with a failing deploy as green: https://github.com/travis-ci/dpl/issues/143#issuecomment-317787190.
