### ISSUE TITLE
resin.models.environmentVariables.device.getAll() only returns service variables?

### ISSUE THREAD

**Issue by nurikabe** [resin-io/resin-sdk#490]
I'm prettty sure that `resin.models.environmentVariables.device.getAll()` used to return regular env vars, but as of yesterday-ish I only seem to be getting service vars back.

Did something change?  Or am I going insane?

I mean, more insane than I already am.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_be03)

**Comment by pimterry** [comment]
@nurikabe which SDK version are you using?

We did do some updates to the API late last week, and I know there've been some variable changes recently that might affect behaviour here. @thgreasi any idea?

**Comment by nurikabe** [comment]
`resin-sdk@8.2.0`

**Comment by thgreasi** [comment]
I will give it a try and come back with some results on this.

**Comment by thgreasi** [comment]
@nurikabe As part of [our multicontainer release](https://resin.io/blog/multicontainer-on-resin-io-is-here/) on 10 March we migrated the environment variables to service variables for our v4 API.
In order to continue supporting older sdk & API consumers that point to the 3rd version of our API (like sdk v8 does) we are doing some transformations under the hood to point to the new device service variable resource.

Initially the multicontainer release didn't contain device env vars, (just configuration vars & service vars).
The app/device env vars that are now available on the dashboard are a new resource that is not reflected back to v8 of the sdk. A new sdk version (v9) with 100% support for multicontainer & the v4 API is currently on beta though!

All in all, you should be able to use the v8 of the sdk without any issue, but all device env var operations on the v8 sdk will actually show up on the dashboard's device configuration & device service variables pages, depending on whether starts with `RESIN_` or not.

Thanks for bringing this up, I've started some internal discussions on this and will report back.
Please give me a note if you face any issues or if you were affected by a change after 10 of March.

**Comment by nurikabe** [comment]
Thanks @thgreasi for the detailed explanation.  Sounds like upgradinig the the v9 beta SDK is the way to go for us.

**Comment by nurikabe** [comment]
@thgrasi Does the v9 beta SDK support env/service variables?  I'm looking through https://github.com/resin-io/resin-sdk/blob/v9.0.0-beta10/DOCUMENTATION.md but I can't seem to find anything.

**Comment by thgreasi** [comment]
@nurikabe No, unfortunately they were removed and will be re-implemented

**Comment by nurikabe** [comment]
@thgreasi Okay, no problem.  Any idea on a rough timeline (+/- a few months..)?  We'll use the to map out our deployment strategy.

**Comment by thgreasi** [comment]
I would hope to get this out sooner than latter but I can't really give an estimate.

**Comment by cdgraff** [comment]
Hi all! same here, we really need this method into the SDK, is vital point to use Multicontainer, now we need to use APIV4 endpoint outside of the SDK only for this feature... and is really dirty solution...
